services:
  mysql:
    build:
      context: .
      dockerfile: mysql/Dockerfile
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "70:80"
    # 👇 이 부분을 정확히 추가해 주셔야 내 컴퓨터의 html 파일들이 도커로 실시간 복사됩니다!
    volumes:
      - ./web/src:/usr/share/nginx/html
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge